name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        uses: mikeal/huggingface-spaces@v2
        with:
          app-id: HRM237/Examen-Git-IABD-Hamad-Rassem-Mahamat-Master-2
          hf-token: ${{ secrets.HF_TOKEN }}
          define-auth: true
