name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

# Force le runner à obtenir les droits d'écriture sur le contenu du dépôt
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Configuration minimale pour éviter les blocages de l'agent Git
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Ajout du dépôt distant et push forcé via le token d'accès
          git remote add space https://huggingface.co/spaces/HRM237/Examen-Git-IABD-Hamad-Rassem-Mahamat-Master-2 || true
          git push --force https://token:$HF_TOKEN@huggingface.co/spaces/HRM237/Examen-Git-IABD-Hamad-Rassem-Mahamat-Master-2 main
