name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # On ne récupère que le tout dernier commit pour aller vite

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Nettoyage agressif des fichiers lourds s'ils existent dans le runner
          rm -f yolo11s-pose.pt model_weights.pt
          
          # 2. Réinitialisation d'un Git propre et isolé dans le runner (sans historique lourd)
          rm -rf .git
          git init
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # 3. On ajoute uniquement les fichiers actuels conformes
          git checkout -b main
          git add .
          git commit -m "Deploy: Production build clean"
          
          # 4. Push écrasant vers Hugging Face
          git remote add space https://huggingface.co/spaces/HRM237/Examen-Git-IABD-Hamad-Rassem-Mahamat-Master-2
          git push --force https://token:$HF_TOKEN@huggingface.co/spaces/HRM237/Examen-Git-IABD-Hamad-Rassem-Mahamat-Master-2 main
